**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [ ]:
## your code(for different question use different cells)
##like Q.1.
#1
import numpy as np
x=np.zeros(10)
print(x)
#2
y=np.ones(10)*5
print(y)
#3
z=np.arange(0,9).reshape(3,3)
print(z)
#4
z=np.random.rand(1)
print(z)
#5
a=np.linspace(0,1,20)
print(a)
#6
a=input("ENTER ANY WORD: ")
x=len(a)
i=0
count=0
for i in range (0,x):
    if a[i]=='a':
        count=count+1


    elif a[i]=='e':
        count=count+1

    elif a[i]=='i':
        count=count+1

    elif a[i]=='o':
        count=count+1

    elif a[i]=='u':
        count=count+1

    else:
        count=count
    i=i+1
print(count)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0.10140163]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
ENTER ANY WORD: helloworld
3


In [ ]:
#Q.1.2
.....

**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [ ]:
##your code
#1
import numpy as np
numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]
for i in range(0,13):
  if numbers[i]%2==0:
    print(numbers[i])
#2
x=np.random.randint(10,100,size=(5,4))
print(x)
#3
x= np.array([[2,3,4,5],[3,6,4,5],[5,6,2,4]])
y= x[1:3,0:3]
print(y)
#5
z= np.arange(1,21).reshape(4,5)
print(z)
z=z.flatten()
print(z)
#6
x=np.random.randint(10,100,size=(5,4))
y=np.random.randint(10,100,size=(5,4))
print(x)
print(y)
z=np.dot(x,y)
print(z)



12
44
102
-8
56
90
-24
48
[[79 44 93 52]
 [46 93 42 52]
 [85 95 38 64]
 [53 40 56 45]
 [88 82 63 14]]
[[3 6 4]
 [5 6 2]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[67 90 60 86]
 [35 99 47 43]
 [93 81 69 73]
 [80 48 29 60]
 [69 31 84 53]]
[[95 30 10 37]
 [43 22 55 51]
 [51 57 44 94]
 [22 94 47 32]
 [52 35 14 24]]
[[162 120  70 123]
 [ 78 121 102  94]
 [144 138 113 167]
 [102 142  76  92]
 [121  66  98  77]]


**Q.3**

(i) Check if matrix multiplication is valid

In [ ]:
def isValid(A,B):


  array1 = np.array(A)
  array2 = np.array(B)
  if array1.shape[1] == array2.shape[0] :
    print("Matrix multiplication is Valid")
  else :
    print("Invalid Input!")
  return isValid

(ii) Using loops (without using numpy)

In [ ]:
def matrix_multiply(A,B):



  array1 = np.array(A)
  array2 = np.array(B)
  box = []
  for i in range(0,array1.shape[0]):
    for j in range(0,array2.shape[1]):
      y=0
      for k  in range(0,array1.shape[1]):
        x = array1[i,k]*array2[k,j]
        y = y+x
      boxes = box.append(y)
      j = j+1
    i = i+1
  array3 = np.array(box)
  array4 = array3.reshape(array1.shape[0],array2.shape[1])
  return array4

**Q.4**
(i) Given:

In [ ]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]
mean=0
for i in range(0,5):
  mean=(mean+ X[i])
print(mean/5)
Z=0
for j in range(0,5):
  Z=(Z+y[j])
print(Z/5)
p=0
for k in range (0,5):
  p=p+(X[k]-mean/5)*(y[k]-Z)
q=0
for l in range (0,5):
  q=q+(X[l]-mean/5)**2
print(p/q)
x=mean/5
m=p/q
y=Z/5
c= y-m*x
print(c)
i= int(input("ENTER ANY NUMBER: "))
print(m*i+c)





3.0
4.0
0.6
2.2
ENTER ANY NUMBER: 6
5.8


Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


##  Pandas


In [7]:
import pandas as pd
x=pd.read_csv("/content/performance_dataset.csv")
#print(x.hours_studied)
#print(x.hours_studied[0])
#print(x.iloc[6:8,0:4])
#print(x.school_type==0)
##print(x.loc[x.school_type==1])
#y=x.dropna()
#z=x.fillna({"school_type":120})
#a=x.dropna(axis=1)
#print(a)
#l=x.rename(columns={"hours_studied":"study"})
#print(l.study)
x['concat'] = x['sports_participation'].astype(str).str.cat(x['uniform'].astype(str), sep =' ')
x

hours_studied  attendance_percent  parent_education  internet_access  \
0          4.743108           79.781453               3.0              NaN   
1         10.992036           97.666558               3.0              1.0   
2          8.848935           57.950598               2.0              0.0   
3          3.481116           84.636899               0.0              0.0   
4          6.264199           58.081774               1.0              0.0   
...             ...                 ...               ...              ...   
4995       4.633189           66.031236               0.0              1.0   
4996       3.744086           54.031024               2.0              0.0   
4997       2.420855           67.916004               3.0              0.0   
4998      10.741467           83.729465               2.0              NaN   
4999       3.938481           89.559193               2.0              0.0   

      school_type  sports_participation  part_time_job  siblings  \
0             NaN                   1.0            0.0       4.0   
1             0.0                   3.0            NaN       1.0   
2             0.0                   1.0            0.0       3.0   
3             0.0                   2.0            0.0       4.0   
4             0.0                   3.0            1.0       2.0   
...           ...                   ...            ...       ...   
4995          2.0                   3.0            1.0       3.0   
4996          NaN                   NaN            1.0       0.0   
4997          1.0                   0.0            0.0       2.0   
4998          0.0                   NaN            1.0       1.0   
4999          0.0                   1.0            1.0       4.0   

      commute_time_mins  favorite_subject  ...   height_cm  weight_kg  \
0             31.681382               2.0  ...  157.398274  53.055261   
1             19.423883               4.0  ...  151.295654  60.628213   
2             28.859972               0.0  ...  183.900640  65.655529   
3             40.083853               1.0  ...  164.835570  38.357323   
4             23.838820               2.0  ...  166.303604  39.271753   
...                 ...               ...  ...         ...        ...   
4995          26.632876               0.0  ...  160.210764  60.125200   
4996          13.090832               4.0  ...  158.662350  52.236613   
4997          27.700626               3.0  ...  147.579151  48.295257   
4998          31.984014               0.0  ...  144.516353  67.014608   
4999           7.913338               0.0  ...  165.746985  48.699774   

      lunch_type  math_tutor  reading_habit  video_game_freq  \
0            0.0         NaN            1.0              0.0   
1            2.0         1.0            1.0              3.0   
2            0.0         1.0            0.0              1.0   
3            2.0         1.0            2.0              1.0   
4            NaN         0.0            1.0              2.0   
...          ...         ...            ...              ...   
4995         2.0         0.0            2.0              1.0   
4996         0.0         0.0            NaN              2.0   
4997         1.0         1.0            3.0              1.0   
4998         1.0         1.0            0.0              2.0   
4999         2.0         NaN            0.0              1.0   

      music_hours_weekly  parent_meeting_freq  uniform   concat  
0               0.898032                  1.0      1.0  1.0 1.0  
1               3.291397                  0.0      0.0  3.0 0.0  
2               0.000000                  2.0      1.0  1.0 1.0  
3               2.410233                  0.0      0.0  2.0 0.0  
4               1.200275                  1.0      1.0  3.0 1.0  
...                  ...                  ...      ...      ...  
4995            6.146414                  2.0      0.0  3.0 0.0  
4996            6.044880                  2.0      1.0  nan 1.0  
4997        

csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).